version: '3.8'

services:
  app:
    build: 
      context: ./docker
      dockerfile: file/Dockerfile 
    container_name: programwithgoi-app74
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./docker/php/config:/usr/local/etc/php
    ports:
      - "8004:8080"
  nginx:
    image: nginx:1.23-alpine
    container_name: programwithgio-nginx74
    restart: always
    ports:
      - "8005:8080"
    volumes:
      - ./src:/var/www/html
      - ./docker/cond.d:/etc/nginx/conf.d
