version: '3.8'

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile 
    container_name: programwithgoi-app74
    restart: always
    working_dir: /var/www/html
    volumes:
      - ../src:/var/www/html
    ports:
      - "8004:8080"
  nginx:
    image: nginx:1.19-alpine
    container_name: programwithgio-nginx74
    restart: always
    ports:
      - "8005:8080"
    volumes:
      - ../src:/var/www/html
      - ./cond.d:/etc/nginx/conf.d
